# Qdrant Configuration
collections:
  default:
    vector_size: 384  # for all-MiniLM-L6-v2
    distance: "Cosine"
    
storage:
  path: "./qdrant_data"
  
service:
  host: "0.0.0.0"
  http_port: 6333
  grpc_port: 6334
